# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self
- task: Docker@2
  inputs:
    containerRegistry: 'acrstorage07'
    repository: 'angularapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
