apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kubernetes07-0c69"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kubernetes07-0c69"
  template:
    metadata:
      labels:
        app: "kubernetes07-0c69"
    spec:
      containers:
        - name: "kubernetes07-0c69"
          image: "acraks07.azurecr.io/kubernetes07"
          ports:
          - containerPort: 80